version: '3.8'

services:
  mcp-security:
    build: .
    ports:
      - "8000:8000"
      - "8443:8443"  # mTLS port
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env
    volumes:
      - ./certs:/certs:ro
      - ./logs:/logs
    depends_on:
      - redis
      - postgres
    networks:
      - mcp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mcp-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mcp_security
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mcp-network

  vault:
    image: vault:latest
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - mcp-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - mcp-network

volumes:
  redis-data:
  postgres-data:
  prometheus-data:

networks:
  mcp-network:
    driver: bridge
